CREATE TABLE defensive_actions (
    player NVARCHAR(100),
    JerseyNumber INT,
    nation NVARCHAR(100),
    pos NVARCHAR(10),
    age NVARCHAR(10),
    min INT,
    tackles_tkl INT,
    tackles_tklw INT,
    tackles_def_3rd INT,
    tackles_mid_3rd INT,
    tackles_att_3rd INT,
    challenges_tkl INT,
    challenges_att INT,
    challenges_tkl_pct INT,
    challenges_lost INT,
    blocks_blocks INT,
    blocks_sh INT,
    blocks_pass INT,
    interceptions INT,
    tkl_int INT,
    clearances INT,
    errors INT,
    game_id NVARCHAR(50),
    player_id NVARCHAR(100),
    team_name NVARCHAR(100),
CONSTRAINT pk_defensive_actions PRIMARY KEY (player_id, game_id),
CONSTRAINT fk_defensive_actions_match FOREIGN KEY (game_id) REFERENCES match_metadata(game_id)
)