CREATE TABLE possession (
    player NVARCHAR(100),
    JerseyNumber INT,
    nation NVARCHAR(100),
    pos NVARCHAR(10),
    age NVARCHAR(10),
    min INT,
    touches_touches INT,
    touches_defpen INT,
    touches_def3rd INT,
    touches_mid3rd INT,
    touches_att3rd INT,
    touches_attpen INT,
    touches_live INT,
    takeons_att INT,
    takeons_succ INT,
    takeons_succ_pct FLOAT,
    takeons_tkld INT,
    takeons_tkld_pct FLOAT,
    carries_carries INT,
    carries_totdist INT,
    carries_prgdist INT,
    carries_prgc INT,
    carries_final_third INT,
    carries_cpa INT,
    carries_mis INT,
    carries_dis INT,
    receiving_rec INT,
    receiving_prgr INT,
    game_id NVARCHAR(50) NOT NULL,
    player_id NVARCHAR(100) NOT NULL,
    team_name NVARCHAR(100),

    CONSTRAINT pk_possession PRIMARY KEY (player_id),
    CONSTRAINT fk_possession FOREIGN KEY (game_id) REFERENCES match_metadata(game_id)
);
