CREATE TABLE pass_types (
    player NVARCHAR(100),
    JerseyNumber INT,
    nation NVARCHAR(100),
    pos NVARCHAR(10),
    age NVARCHAR(10),
    min INT,
    att INT,
    pass_types_live INT,
    pass_types_dead INT,
    pass_types_fk INT,
    pass_types_tb INT,
    pass_types_sw INT,
    pass_types_crs INT,
    pass_types_ti INT,
    pass_types_ck INT,
    corner_kicks_in INT,
    corner_kicks_out INT,
    corner_kicks_str INT,
    outcomes_cmp INT,
    outcomes_off INT,
    outcomes_blocks INT,
    game_id NVARCHAR(50) NOT NULL,
    player_id NVARCHAR(100) NOT NULL,
    team_name NVARCHAR(100),

CONSTRAINT pk_pass_types PRIMARY KEY (player_id),
CONSTRAINT fk_pass_types FOREIGN KEY (game_id) REFERENCES match_metadata(game_id)
);
