CREATE TABLE summary_stats (
    Player NVARCHAR(50),
    JerseyNumber INT,
    Nation NVARCHAR(50) NULL,
    Pos NVARCHAR(50),
    Age NVARCHAR(50) NULL,
    Min INT,
    Gls INT,
    Ast INT,
    PK INT,
    PKatt INT,
    Sh INT,
    SoT INT,
    CrdY INT,
    CrdR INT,
    Touches INT,
    Tkl INT,
    Int INT,
    Blocks INT,
    xG DECIMAL(4, 2),
    npxG DECIMAL(4, 2),
    xAG DECIMAL(4, 2),
    SCA INT,
    GCA INT,
    Cmp INT,
    Att INT,
    CmpPct DECIMAL(5, 2),
    PrgP INT,
    Carries INT,
    PrgC INT,
    Succ INT,
    game_id NVARCHAR(50),
    player_id NVARCHAR(50),
    CONSTRAINT PK_SUMMARY_STATS PRIMARY KEY (player_id),
    CONSTRAINT FK_SUMMARY_STATS_game_id FOREIGN KEY (game_id) REFERENCES match_metadata(game_id)
);
