CREATE TABLE misc_stats (
    player NVARCHAR(100),
    JerseyNumber INT,
    nation NVARCHAR(100),
    pos NVARCHAR(10),
    age NVARCHAR(10),
    min INT,
    performance_crdy INT,
    performance_crdr INT,
    performance_2crdy INT,
    performance_fls INT,
    performance_fld INT,
    performance_off INT,
    performance_crs INT,
    performance_int INT,
    performance_tklw INT,
    performance_pkwon INT,
    performance_pkcon INT,
    performance_og INT,
    performance_recov INT,
    arial_duel_won INT,
    arial_duel_lost INT,
    arial_duel_won_pct INT,
    game_id NVARCHAR(50) NOT NULL,
    player_id NVARCHAR(100) NOT NULL,
    team_name NVARCHAR(100),

CONSTRAINT pk_misc_stats PRIMARY KEY (player_id),
CONSTRAINT fk_misc_stats_match FOREIGN KEY (game_id) REFERENCES match_metadata(game_id)
);
